---
#/home/daniecom/public_html/resources/projects/websiteDesign
deployment:
  tasks: 
    - export DEPLOYPATH=/home/daniecom/public_html/resources/projects/websiteDesign
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    