---
#/home/daniecom/public_html/resources/projects/websiteDesign
deployment:
  tasks: 
    - export DEPLOYPATH=/home/daniecom/public_html/resources/projects/teaCozy
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R resources $DEPLOYPATH
    